;;
;; The imports is responsible for enumerating our list of imports
;;


(define-alias Activity android.app.Activity)
(define-alias Bitmap android.graphics.Bitmap)
(define-alias BitmapFactory android.graphics.BitmapFactory)
(define-alias BluetoothAdapter android.bluetooth.BluetoothAdapter)
(define-alias BluetoothDevice android.bluetooth.BluetoothDevice)
(define-alias BluetoothSocket android.bluetooth.BluetoothSocket)
(define-alias Camera android.hardware.Camera)
(define-alias CameraAutoFocusCallback android.hardware.Camera$AutoFocusCallback)
(define-alias CameraCharacteristics android.hardware.camera2.CameraCharacteristics)
(define-alias CameraDevice android.hardware.camera2.CameraDevice)
(define-alias CameraDeviceStateCallback android.hardware.camera2.CameraDevice$StateCallback)
(define-alias CameraManager android.hardware.camera2.CameraManager)
(define-alias CameraPictureCallback android.hardware.Camera$PictureCallback)
(define-alias Color android.graphics.Color)
(define-alias Context android.content.Context)
(define-alias Date java.util.Date)
(define-alias File java.io.File)
(define-alias FileInputStream java.io.FileInputStream)
(define-alias FileOutputStream java.io.FileOutputStream)
(define-alias Handler android.os.Handler)
(define-alias Iterator java.util.Iterator)
(define-alias Log android.util.Log)
(define-alias Matrix android.graphics.Matrix)
(define-alias Message android.os.Message)
(define-alias MotionEvent android.view.MotionEvent)
(define-alias OutputStream java.io.OutputStream)
(define-alias PrintStream java.io.PrintStream)
(define-alias Random java.util.Random)
(define-alias Set java.util.Set)
(define-alias SurfaceTexture android.graphics.SurfaceTexture)
(define-alias TextureView android.view.TextureView)
(define-alias TextureViewListener android.view.TextureView$SurfaceTextureListener)
(define-alias Thread java.lang.Thread)
(define-alias Throwable java.lang.Throwable)
(define-alias ViewOnLongClickListener android.view.View$OnLongClickListener)
(define-alias ViewOnTouchListener android.view.View$OnTouchListener)

